name: Build, Test, Code Coverage, and Push Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (using the Temurin distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Confirm Java version is 17
      - name: Check Java version
        run: java -version

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 5: Install JaCoCo plugin for code coverage
      - name: Install JaCoCo plugin
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent

      # Step 6: Run tests with Maven
      - name: Run tests with Maven
        run: mvn test

      # Step 7: Generate code coverage report using JaCoCo
      - name: Generate code coverage report
        run: mvn jacoco:report

      # Step 8: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GHCR_PAT }}  # GitHub Personal Access Token (PAT)

      # Step 9: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/hello-api:latest .

      # Step 10: Push Docker image to GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/hello-api:latest
