name: Build, Test, Code Coverage, and Push Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 2: Run tests with Maven
      - name: Run tests with Maven
        run: mvn test

      # Step 3: Generate code coverage report using JaCoCo
      - name: Generate code coverage report
        run: mvn jacoco:report

      # Step 4: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GHCR_PAT }}  # GitHub Personal Access Token (PAT)

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/hello-api:latest .

      # Step 6: Push Docker image to GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/hello-api:latest
